### PR TITLE
rename study

### PR DESCRIPTION
**Pull request by AbdelHedhili**
Signed-off-by: AbdelHedhili <abdelsalem.hedhili@rte-france.com>

### CODE REVIEW

**Comment by jonenst** [comment]
What about doing like the github API ? for example
https://developer.github.com/v3/repos/#transfer-a-repository
POST /repos/:owner/:repo/transfer
```json
{
  "new_owner": "github"
}
```

**Comment by jonenst** [comment]
Or PATCH or POST on /studies/{studyName} with a json body containing the params to modify is fine

**Comment by geofjamg** [comment]
Ok, let's go for:

POST on /studies/{studyName}/rename

with body:

{
    newName: "toto"
}

**Comment by jonenst** [comment]
So for fields that don't modify the URL (e.g. description), we do
```
POST on /studies/{studyName}
{
  "description": "xxx",
  "otherfield": "yyy"
}
```
and for special fields like name (because it modifies the url of the resource), we do 
```
POST on /studies/{studyName}/XXX
{
"newname": "xxx"
}
```
?

**Comment by geofjamg** [comment]
Yes!

**Pull request merged**
